// Code generated by generators/generate-bindings.mjs; DO NOT EDIT.
package artifact

var ArtifactValueTypes = []string{
	"text",
	"number",
	"boolean",
	"currency",
	"date",
	"datetime",
	"time",
	"location",
	"file",
	"image",
	"video",
	"audio",
	"link",
	"structured",
	"reference",
	"signature",
	"collection",
}

var ArtifactSourceTypes = []string{
	"inline",
	"local",
	"object",
	"url",
	"hosted",
	"provider",
}

var LocalArtifactSyncStates = []string{
	"local_only",
	"pending_upload",
	"uploading",
	"uploaded",
	"failed",
}

var ArtifactIntegrityAlgorithms = []string{
	"sha256",
	"sha384",
	"sha512",
}

var ArtifactConditionKinds = []string{
	"state",
	"actor",
	"artifact_exists",
	"artifact_value",
	"and",
	"or",
	"not",
}

var ArtifactValueOperators = []string{
	"eq",
	"neq",
	"gt",
	"gte",
	"lt",
	"lte",
	"contains",
	"in",
}

var ArtifactPrivacyClassifications = []string{
	"public",
	"internal",
	"private",
	"sensitive",
	"restricted",
}

var ArtifactPrivacyRepresentations = []string{
	"hidden",
	"masked",
	"approximate",
	"full",
}

var ArtifactVerificationStatuses = []string{
	"pending",
	"verified",
	"rejected",
	"waived",
}
